### ISSUE TITLE
Need API connection - assign hardware and unassign hardware to plant groups

### ISSUE THREAD

**Issue by elid86** [zachlefevre/greenalytics_services#56]

**Comment by zachlefevre** [comment]
@cdman678 Coud you implement a method in the DB classlib to make this association? A table like "hasHardware"

**Comment by zachlefevre** [comment]
both completed;
    [Route("api/{accountID}")]
        [HttpDelete("plantGroup/{plantGroupName}/hardware/{hardwareID}")]
        [HttpPost("plantGroup/{plantGroupName}/hardware/{hardwareID}")]
